komodo_1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  back_right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: komodo_1_RR_Wheel_joint
    pid: {p: 0.0, i: 0.00, d: 0}
  back_left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: komodo_1_RL_Wheel_joint
    pid: {p: 0.0, i: 0.00, d: 0}
  front_right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: komodo_1_FR_Wheel_joint
    pid: {p: 0.0, i: 0.00, d: 0}
  front_left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: komodo_1_FL_Wheel_joint
    pid: {p: 0.0, i: 0.00, d: 0}
  base_rotation_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_1_base_rotation_joint
    pid: {p: 500.0, i: 0.00, d: 0}
  shoulder_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_1_shoulder_joint
    pid: {p: 500.0, i: 0, d: 0.0}
  elbow1_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_1_elbow1_joint
    pid: {p: 700.0, i: 0, d: 0.0}
  elbow2_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_1_elbow2_joint
    pid: {p: 700.0, i: 0, d: 0.0}
  wrist_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_1_wrist_joint
    pid: {p: 500.0, i: 0.0, d: 0.0}
  left_finger_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_1_left_finger_joint
    pid: {p: 500.0, i: 0.0, d: 0.0}
  right_finger_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_1_right_finger_joint
    pid: {p: 20.0, i: 0.0, d: 0.0}
  elevator_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_1_elevator_joint
    pid: {p: 20.0, i: 0.0, d: 0.0}

  # trajectory Controllers -> keeps constant velocity of the joints between two points
  komodo_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - base_rotation_joint
      - shoulder_joint
      - elbow1_joint
      - elbow2_joint
      - wrist_joint  
    gains: # Required because we're controlling an effort interface
      base_rotation_joint: {p: 500.0, i: 0.0, d: 0.0}
      shoulder_joint:      {p: 500.0, i: 0.0, d: 0.0}
      elbow1_joint:        {p: 700.0, i: 0.0, d: 0.0}
      elbow2_joint:        {p: 700.0, i: 0.0, d: 0.0}
      wrist_joint:         {p: 500.0, i: 0.0, d: 0.0}
    
  komodo_gripper_controller:
    type: gripper_action_controller
    joints: 
      - komodo_1_right_finger_joint
#    goal_tolerance: 0.01
#    stalled_velocity_threshold: 0.01
#    stall_timeout: 0.2




