// Generated by gencpp from file ric_board/IMUClib.msg
// DO NOT EDIT!


#ifndef RIC_BOARD_MESSAGE_IMUCLIB_H
#define RIC_BOARD_MESSAGE_IMUCLIB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace ric_board
{
template <class ContainerAllocator>
struct IMUClib_
{
  typedef IMUClib_<ContainerAllocator> Type;

  IMUClib_()
    : max()
    , min()  {
    }
  IMUClib_(const ContainerAllocator& _alloc)
    : max(_alloc)
    , min(_alloc)  {
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _max_type;
  _max_type max;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _min_type;
  _min_type min;




  typedef boost::shared_ptr< ::ric_board::IMUClib_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ric_board::IMUClib_<ContainerAllocator> const> ConstPtr;

}; // struct IMUClib_

typedef ::ric_board::IMUClib_<std::allocator<void> > IMUClib;

typedef boost::shared_ptr< ::ric_board::IMUClib > IMUClibPtr;
typedef boost::shared_ptr< ::ric_board::IMUClib const> IMUClibConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ric_board::IMUClib_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ric_board::IMUClib_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ric_board

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ric_board': ['/home/nir/bgumodo_ws/src/ric/ric_board/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::IMUClib_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::IMUClib_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::IMUClib_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::IMUClib_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::IMUClib_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::IMUClib_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ric_board::IMUClib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "564e1f3d44af5b9d73226679d298f9f8";
  }

  static const char* value(const ::ric_board::IMUClib_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x564e1f3d44af5b9dULL;
  static const uint64_t static_value2 = 0x73226679d298f9f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ric_board::IMUClib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ric_board/IMUClib";
  }

  static const char* value(const ::ric_board::IMUClib_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ric_board::IMUClib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 max\n\
geometry_msgs/Vector3 min\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::ric_board::IMUClib_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ric_board::IMUClib_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max);
      stream.next(m.min);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct IMUClib_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ric_board::IMUClib_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ric_board::IMUClib_<ContainerAllocator>& v)
  {
    s << indent << "max: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.max);
    s << indent << "min: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.min);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIC_BOARD_MESSAGE_IMUCLIB_H
